version: "3.7"
services:
  api-gateway:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - "node.hostname == api-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:15
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.role==worker"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - traefik-public
  api:
    image: jung2k/hello-world:latest
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`intern.nexlab.tech`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
    networks:
      - traefik-public
    depends_on:
      - api-gateway
networks:
  traefik-public:
    external: true
