version: "3.7"
services:
  api-gateway:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "9000:9000"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - "node.hostname == api-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: jung2k/hello-world:latest
    ports:
      - "9000:9000"
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
          - "node.hostname != api-gateway"
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=api"
      - "traefik.http.services.api.loadbalancer.server.port=9000"
    networks:
      - traefik-public
    depends_on:
      - api-gateway
networks:
  traefik-public:
    external: true
