version: "3.7"
services:
  traefik:
    image: traefik:latest
    command:
      - --api.insecure
      - --api.dashboard
      - --providers.docker
      - --providers.docker.watch
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - "node.role == manager"
          - "node.hostname == api-gateway"
  app:
    image: jung2k/hello-world:latest
    ports:
      - 3000
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.tls=true"
        - "traefik.http.routers.app.tls.certresolver=letsencrypt"
        - "traefik.http.routers.app.entrypoints=http"
        - "traefik.http.routers.app.rule=PathPrefix(`/app`)"
        - "traefik.http.routers.app.service=app-svc"
        - "traefik.http.services.app-svc.loadbalancer.server.port=3000"
    environment:
      NODE_HOSTNAME: "{{.Node.Hostname}}"