version: "3.7"
services:
  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=tcp://127.0.0.1:2377
      - --providers.docker.exposedbydefault=false
      - --accessLog=true
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == api-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:15
    labels:
      - "traefik.enable=false"
    ports:
      - 5432:5432
    networks:
      - traefik-public
    deploy:
      placement:  
        constraints:
          - "node.role==worker"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  hello:
    image: jung2k/hello-world:latest
    labels:
      - "traefik.enable=true"
    ports:
      - 3000:3000
    networks:
      - traefik-public
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
      labels:
        - "traefik.http.routers.hello.rule=PathPrefix(`/hello`)"
        - "traefik.http.services.hello.loadbalancer.server.port=3000"
networks:
  traefik-public:
    external: true  
