version: "3.7"
services:
  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accessLog=true
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - "node.hostname == api-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.role==worker"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    image: jung2k/hello-world:latest
    ports:
      - 3000
    networks:
      - traefik-public
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.hello_http.rule=Host(`intern.nexlab.tech`)"
        - "traefik.http.routers.hello_http.entrypoints=http"
        - "traefik.http.routers.hello_http.service=hello"
        - "traefik.http.services.hello.loadbalancer.server.port=3000"
        - "traefik.http.services.hello.loadbalancer.passhostheader=true"
networks:
  traefik-public:
    external: true
