version: "3.7"
services:
  traefik:
    image: traefik:latest
    # command:
    #   - --providers.docker=true
    #   - --providers.docker.swarmMode=true
    #   - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - "node.hostname == api-gateway"
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.role==worker"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  hello:
    image: jung2k/hello-world:latest
    container_name: hello
    networks:
      - traefik-public
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
networks:
  traefik-public:
    external: true
