api:
  insecure: true
  dashboard: true
  debug: true
log:
  level: DEBUG #INFO
  format: json
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
  api:
    address: ":8080"
providers:
  file:
    directory: "/conf"
    filename: "dynamic_conf.yaml"
    watch: true
